stages:
  - test

variables:
  CONDA_HOME: "/public/home/zyye/miniconda3"
  CONDA_ENV_NAME: "/public/home/zyye/miniconda3/envs/pyrinst"

before_script:
  - source ${CONDA_HOME}/etc/profile.d/conda.sh
  - conda activate $CONDA_ENV_NAME
  - echo "Current Conda Environment:"
  - conda info --envs | grep '*'
  - python --version
  - pip install -e .

unit_test:
  stage: test
  script:
    - pytest tests/unittest --ignore=tests/unittest/test_mace.py

# examples_test:
#   stage: test
#   script:
#     - pytest examples/
