# tests/test_elements.py

import logging
from typing import Any, Dict

import pytest

from easy_instanton.utils.elements import element_data

# Define mock data at the module level for clarity and reuse.
MOCK_DATA: Dict[str, Any] = {
    "elements": {
        "H": {
            "atomicNumber": 1,
            "mass": 1.008,
            "isotopes": {
                "1": {"mass": 1.007825},
                "2": {"mass": 2.014102},
            },
        },
        "C": {
            "atomicNumber": 6,
            "mass": 12.011,
            "isotopes": {
                "12": {"mass": 12.0},
                "13": {"mass": 13.003355},
            },
        },
    },
    "isotope_aliases": {"D": {"element": "H", "massNumber": 2}},
}


@pytest.fixture
def mocked_element_data(monkeypatch: pytest.MonkeyPatch) -> None:
    """A pytest fixture to mock the data within the element_data instance.

    This fixture uses `monkeypatch` to temporarily replace the internal data
    dictionaries of the `element_data` singleton instance for the duration
    of a test. This ensures that tests are isolated, repeatable, and do not
    depend on the external JSON file.

    Parameters
    ----------
    monkeypatch : pytest.MonkeyPatch
        A built-in pytest fixture for safely modifying classes, methods,
        or variables.
    """
    monkeypatch.setattr(element_data, "_elements", MOCK_DATA["elements"])
    monkeypatch.setattr(element_data, "_aliases", MOCK_DATA["isotope_aliases"])


@pytest.mark.parametrize(
    "symbol, expected_mass",
    [
        ("C", 12.011),  # Conventional mass
        ("H", 1.008),  # Conventional mass
        ("D", 2.014102),  # Isotope mass via alias
        ("C13", 13.003355),  # Isotope mass via pattern
        ("H1", 1.007825),  # Isotope mass via pattern
    ],
)
def test_get_mass_happy_paths(
    mocked_element_data: None, symbol: str, expected_mass: float
) -> None:
    """Tests successful retrieval of various masses.

    This test is parameterized to cover multiple valid scenarios efficiently,
    including lookups for conventional mass, alias-based isotopes, and
    pattern-based isotopes.

    Parameters
    ----------
    mocked_element_data : None
        This argument activates the fixture to load mock data.
    symbol : str
        The atomic symbol to be tested.
    expected_mass : float
        The expected mass for the given symbol.
    """
    actual_mass = element_data.get_mass(symbol)
    assert abs(actual_mass - expected_mass) < 1e-9, (
        f"Mass for symbol '{symbol}' did not match expected value."
    )


@pytest.mark.parametrize(
    "symbol, expected_z",
    [
        ("C", 6),
        ("C13", 6),
        ("H", 1),
        ("D", 1),
    ],
)
def test_get_atomic_number_happy_paths(
    mocked_element_data: None, symbol: str, expected_z: int
) -> None:
    """Tests successful retrieval of atomic numbers.

    This test is parameterized to verify that various symbol types all
    correctly resolve to the same, correct atomic number for an element.

    Parameters
    ----------
    mocked_element_data : None
        This argument activates the fixture to load mock data.
    symbol : str
        The atomic symbol to be tested.
    expected_z : int
        The expected atomic number for the given symbol.
    """
    actual_z = element_data.get_atomic_number(symbol)
    assert actual_z == expected_z, (
        f"Atomic number for symbol '{symbol}' did not match expected value."
    )


@pytest.mark.parametrize(
    "invalid_symbol",
    [
        "Xyz",  # Completely invalid element
        "C99",  # Valid element, but non-existent isotope
        "d",  # Incorrect case for alias
    ],
)
def test_get_mass_raises_keyerror_for_invalid_symbols(
    mocked_element_data: None, invalid_symbol: str
) -> None:
    """Verifies that KeyError is raised for various invalid symbols.

    This parameterized test ensures that the system is robust against different
    types of incorrect user input.

    Parameters
    ----------
    mocked_element_data : None
        This argument activates the fixture to load mock data.
    invalid_symbol : str
        The invalid symbol that is expected to cause a KeyError.
    """
    with pytest.raises(KeyError):
        element_data.get_mass(invalid_symbol)


def test_logging_for_invalid_symbol(
    mocked_element_data: None, caplog: pytest.LogCaptureFixture
) -> None:
    """Tests that an ERROR message is logged for an invalid symbol.

    This test demonstrates how to use the `caplog` fixture to inspect
    log messages generated by the code under test.

    Parameters
    ----------
    mocked_element_data : None
        This argument activates the fixture to load mock data.
    caplog : pytest.LogCaptureFixture
        A built-in pytest fixture that captures logging output.
    """
    with caplog.at_level(logging.ERROR):
        with pytest.raises(KeyError):
            element_data.get_mass("Xyz")

    # Assert that the specific error message we expect is present in the logs.
    assert "not a valid element" in caplog.text
